// source: diagnoses.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var model_pb = require('./model_pb.js');
goog.object.extend(proto, model_pb);
var types_pb = require('./types_pb.js');
goog.object.extend(proto, types_pb);
goog.exportSymbol('proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest', null, global);
goog.exportSymbol('proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest.displayName = 'proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse.displayName = 'proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    uuid: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest}
 */
proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest;
  return proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest}
 */
proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUuid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUuid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string uuid = 1;
 * @return {string}
 */
proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest.prototype.getUuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest} returns this
 */
proto.leishmaniapp.cloud.diagnoses.DiagnosisRequest.prototype.setUuid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: (f = msg.getStatus()) && types_pb.StatusResponse.toObject(includeInstance, f),
    diagnosis: (f = msg.getDiagnosis()) && model_pb.Diagnosis.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse}
 */
proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse;
  return proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse}
 */
proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new types_pb.StatusResponse;
      reader.readMessage(value,types_pb.StatusResponse.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 2:
      var value = new model_pb.Diagnosis;
      reader.readMessage(value,model_pb.Diagnosis.deserializeBinaryFromReader);
      msg.setDiagnosis(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      types_pb.StatusResponse.serializeBinaryToWriter
    );
  }
  f = message.getDiagnosis();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      model_pb.Diagnosis.serializeBinaryToWriter
    );
  }
};


/**
 * optional leishmaniapp.cloud.types.StatusResponse status = 1;
 * @return {?proto.leishmaniapp.cloud.types.StatusResponse}
 */
proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse.prototype.getStatus = function() {
  return /** @type{?proto.leishmaniapp.cloud.types.StatusResponse} */ (
    jspb.Message.getWrapperField(this, types_pb.StatusResponse, 1));
};


/**
 * @param {?proto.leishmaniapp.cloud.types.StatusResponse|undefined} value
 * @return {!proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse} returns this
*/
proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse} returns this
 */
proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional leishmaniapp.cloud.model.Diagnosis diagnosis = 2;
 * @return {?proto.leishmaniapp.cloud.model.Diagnosis}
 */
proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse.prototype.getDiagnosis = function() {
  return /** @type{?proto.leishmaniapp.cloud.model.Diagnosis} */ (
    jspb.Message.getWrapperField(this, model_pb.Diagnosis, 2));
};


/**
 * @param {?proto.leishmaniapp.cloud.model.Diagnosis|undefined} value
 * @return {!proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse} returns this
*/
proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse.prototype.setDiagnosis = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse} returns this
 */
proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse.prototype.clearDiagnosis = function() {
  return this.setDiagnosis(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.leishmaniapp.cloud.diagnoses.DiagnosisResponse.prototype.hasDiagnosis = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.leishmaniapp.cloud.diagnoses);
